name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: User Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: npm install and npm test
        run: |
          npm i
          npm run lint
          npm run test

  build:
    needs: test-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2
      - name: User Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: npm build
        run: |
          npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./dist/test-new-pipeline/
          remote_path: /home/ubuntu/my-app
          remote_host: "${{ secrets.SERVER_HOST }}"
          remote_user: "${{ secrets.USERNAME }}"
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
